function handle=prettyBarPlot(vals,names,thexlabelstring,numberPerCondition)

	% handle=prettyBarPlot(vals,names,thexlabelstring,numberPerCondition)
	%
	% Inputs-
	%	vals               = vector containing the correlation values you want to plot
	%	names              = cell array of strings containing names for each case
	%	thexlabelstring    = string for the x-axis label
	%	numberPerCondition = the number of cases that you used to compute each correlation (for computing the confidence interval); specify as zero or false to skip

if nargin<4
	numberPerCondition=112;
end
if nargin<3
	thexlabelstring='|r_p|';
end

accentColor=0.5;
mainBarColor=0.2;
fontSize=20;

figure('color','white');
hold on;

handle=barh(vals,0.7,'FaceColor',mainBarColor*[1 1 1],'Edgecolor',accentColor*[1 1 1]);

set(gca,...
	'TickDir','out',...
	'XGrid','on',...
	'YLim',[0.5 length(vals)+0.5],...
	'YLimMode','manual',...
	'YTickMode','manual',...
	'YTick',1:length(vals),...
	'YTickLabelMode','manual',...
	'YTickLabel',names,...
	'FontSize',fontSize,...
	'FontName','Helvetica Neue',...
	'FontWeight','normal',...
	'GridLineStyle','-',...
	'Box','off');
set(handle,'ShowBaseLine','off',...
	'LineWidth',1.2);
xlabel(['$' thexlabelstring '$'],...
	'interpreter','latex',...
	'FontSize',30);

% Add confidence intervals
if numberPerCondition>0
	confInt=intervalEstimationOfCorrCoeff(vals,numberPerCondition); % 95% confidence by default
	errorHandle=errorbar_x(vals(:).',1:length(vals),...
		vals(:).'-confInt(:,1).',confInt(:,2).'-vals(:).','k-');
	set(errorHandle,...
		'LineWidth',1.75,...
		'Color',accentColor*[1 1 1]);
end

% Add text labels of the values
for ii=1:length(vals)
	if exist('confInt','var')
		xPosForText=confInt(ii,2);
	else
		xPosForText=vals(ii);
	end
	defaultXaxisLength=diff(get(gca,'XLim'));
	text(xPosForText+0.02*defaultXaxisLength,ii,...
		sprintf('%1.2f',vals(ii)),...
		'FontSize',fontSize,...
		'FontName','Helvetica Neue',...
		'FontWeight','bold');
end
