function handle=prettyBarPlot(vals,names,thexlabelstring,numberPerCondition)

	% handle=prettyBarPlot(vals,names,thexlabelstring,numberPerCondition)
	%
	% Inputs-
	%	vals               = vector containing the correlation values you want to plot
	%	names              = cell array of strings containing names for each case
	%	thexlabelstring    = string for the x-axis label
	%	numberPerCondition = the number of cases that you used to compute each correlation (for computing the confidence interval)

if nargin<4
	numberPerCondition=112;
end
if nargin<3
	thexlabelstring='|r_p|';
end

accentColor=0.5;
mainBarColor=0.2;

figure('color','white');
hold on;

handle=barh(vals,0.5,'FaceColor',mainBarColor*[1 1 1],'Edgecolor',accentColor*[1 1 1]);

set(gca,...
	'TickDir','out',...
	'XGrid','on',...
	'XLim',[0 1],...
	'YLim',[0.5 length(vals)+0.5],...
	'YLimMode','manual',...
	'YTickMode','manual',...
	'YTick',1:length(vals),...
	'YTickLabelMode','manual',...
	'YTickLabel',names,...
	'FontSize',16,...
	'FontName','Helvetica Neue',...
	'FontWeight','bold',...
	'GridLineStyle','-',...
	'Box','off');
set(handle,'ShowBaseLine','off',...
	'LineWidth',1.2);
xlabel(['$' thexlabelstring '$'],...
	'interpreter','latex',...
	'FontSize',18);

rho=intervalEstimationOfCorrCoeff(vals,numberPerCondition);
errorHandle=errorbar_x(vals(:).',1:length(vals),...
	vals(:).'-rho(:,1).',rho(:,2).'-vals(:).','k-');
set(errorHandle,...
	'LineWidth',3,...
	'Color',accentColor*[1 1 1]);

set(gcf,'Position',[680 450 510 650]);
